package scanner

import (
	"os"
	"path/filepath"
	"testing"
)

// False positives from the AI Learning report.
func TestDataFilesAndFalsePositives(t *testing.T) {
	s := newScanner(t)
	cfg := s.Settings.Get().Scanner
	home := t.TempDir()
	check := func(rel, content string) *Detection {
		t.Helper()
		p := filepath.Join(home, rel)
		os.MkdirAll(filepath.Dir(p), 0o755)
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
		info, _ := os.Stat(p)
		d, _ := s.CheckFile(p, info, cfg)
		return d
	}
	// Analog's cache quotes every attack URL; it is not code.
	logLine := `GET /index.php?x=` + j("<?php ev", `al($_GET["c"]); ?>`) + " 404\n"
	if d := check("tmp/analog/ssl/example.com/cache", logLine); d != nil {
		t.Fatalf("analog cache flagged: %+v", d)
	}
	// A PHP file there is still scanned.
	if d := check("tmp/analog/x.php", j("<?php ev", `al($_POST["c"]);`)); d == nil {
		t.Fatal("PHP file in a stats folder skipped")
	}
	// WordPress PHP translation files.
	l10n := "<?php\n// generated by WordPress\nreturn ['domain'=>'wordfence','plural-forms'=>'nplurals=2; plural=(n != 1);','messages'=>['Scan'=>'Scan','Run (now)'=>'Run (now)','a.' . 'b'=>'x']];\n"
	if !translationFile(filepath.Join(home, "public_html/wp-content/languages/plugins/wordfence-en_GB.l10n.php"), []byte(l10n)) {
		t.Fatal("translation file not recognised")
	}
	for _, bad := range []string{
		"<?php return ['a'=>'b']; " + j("ev", `al($_POST['x']);`),
		"<?php return ['a'=>" + j("base6", "4_decode('eA==')") + "];",
		"<?php return ['a'=>'b'];\n<?php echo 1;",
	} {
		if translationFile(filepath.Join(home, "public_html/wp-content/languages/x.l10n.php"), []byte(bad)) {
			t.Errorf("code accepted as a translation file: %q", bad)
		}
	}
	if translationFile(filepath.Join(home, "public_html/x.l10n.php"), []byte(l10n)) {
		t.Error("translation file outside a languages folder")
	}
	// PsySH's offline manual.
	if !dataFile(filepath.Join(home, ".local/share/psysh/php_manual.php"), ".php") || dataFile(filepath.Join(home, ".local/share/psysh/x.php"), ".php") {
		t.Error("psysh manual")
	}
	// A fingerprinting library that only lists miner names is not a miner.
	fp := `var blockers=["coinhive","cryptoloot","CoinImp","deepMiner"];function detect(){return blockers.filter(function(n){return window[n]})}`
	if d := check("public_html/wp-content/plugins/pay/js/fp.min.js", fp); d != nil {
		t.Fatalf("fingerprint library flagged: %+v", d)
	}
	if d := check("public_html/m.js", malicious["miner.js"]); d == nil || d.Signature != "JS.Miner.Browser" {
		t.Fatalf("miner not flagged: %+v", d)
	}
	// An application's user controller: password, PIN and OTP fields, mails the user.
	users := `<?php class Users { function register() { $ip = $_SERVER['REMOTE_ADDR'];
	$p = $_POST['password']; $c = $_POST['confirm_password']; $o = $_POST['otp']; $n = $_POST['pin'];
	mail($email, 'Welcome', 'Your account is ready'); } }`
	if d := check("public_html/app/controllers/Users.php", users); d != nil && d.Signature == "Phishing.Collector" {
		t.Fatal("user controller flagged as a phishing collector")
	}
}
